<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Axolotl2D\Axolotl2D.csproj" />
    <PackageReference Include="Microsoft.Build.Framework" Version="17.14.28" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.14.28" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <None Include="build\Axolotl2D.MSBuild.targets" Pack="true" PackagePath="build\Axolotl2D.MSBuild.targets" />
  </ItemGroup>
</Project>
