using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Axolotl2D.Packages;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;

namespace Axolotl2D.MSBuild;

public sealed class GenerateAxolotlModuleSource : Microsoft.Build.Utilities.Task
{
    [Required] public string OutputPath { get; set; } = null!;
    public ITaskItem[] AssetLoaders { get; set; } = [];
    [Output] public string GeneratedPath => OutputPath;

    public override bool Execute()
    {
        try
        {
            var source = new StringBuilder("// <auto-generated />\nnamespace Axolotl2D.Generated;\n")
                .Append("public sealed class AxolotlGeneratedModuleRegistration : global::Axolotl2D.Packages.IAxolotlModuleRegistration\n{\n")
                .Append("    public void Register(global::Axolotl2D.Packages.AxolotlModuleContext context)\n    {\n");
            foreach (var loader in AssetLoaders)
            {
                var assetType = loader.GetMetadata("AssetType");
                var loaderType = loader.GetMetadata("LoaderType");
                if (string.IsNullOrWhiteSpace(assetType) || string.IsNullOrWhiteSpace(loaderType))
                    throw new InvalidOperationException("AxolotlAssetLoader requires AssetType and LoaderType metadata.");
                source.Append("        context.RegisterAssetLoader(typeof(global::").Append(assetType)
                    .Append("), typeof(global::").Append(loaderType).Append("));\n");
            }
            source.Append("    }\n}\n");
            Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(OutputPath))!);
            var text = source.ToString();
            if (!File.Exists(OutputPath) || File.ReadAllText(OutputPath) != text)
                File.WriteAllText(OutputPath, text, new UTF8Encoding(false));
            return true;
        }
        catch (Exception exception)
        {
            Log.LogErrorFromException(exception, showStackTrace: true);
            return false;
        }
    }
}

public sealed class PackAxolotlModule : Microsoft.Build.Utilities.Task
{
    [Required] public string OutputPath { get; set; } = null!;
    [Required] public string AssemblyPath { get; set; } = null!;
    [Required] public string PackageId { get; set; } = null!;
    [Required] public string PackageVersion { get; set; } = null!;
    public string? Entrypoint { get; set; }
    public string? SignerId { get; set; }
    public string? SigningKeyPath { get; set; }
    public ITaskItem[] Assets { get; set; } = [];
    public ITaskItem[] Dependencies { get; set; } = [];
    public ITaskItem[] ModuleAssemblies { get; set; } = [];

    public override bool Execute()
    {
        try
        {
            var assemblyEntry = "$module/" + Path.GetFileName(AssemblyPath);
            var assetMetadata = Assets.Select(item => new AxolotlPackageAsset(item.GetMetadata("Name"),
                item.GetMetadata("EntryName"), item.GetMetadata("RuntimeType"),
                JsonSerializer.Deserialize<string[]>(item.GetMetadata("DependenciesJson")) ?? [])).ToArray();
            var dependencies = Dependencies.Select(item =>
            {
                var id = item.GetMetadata("AxolotlPackageId");
                var version = item.GetMetadata("AxolotlPackageVersion");
                if (string.IsNullOrWhiteSpace(id) || string.IsNullOrWhiteSpace(version))
                    throw new InvalidOperationException($"Module reference '{item.ItemSpec}' requires AxolotlPackageId and AxolotlPackageVersion metadata.");
                return new AxolotlPackageDependency(id, version);
            }).ToArray();
            var manifest = new AxolotlPackageManifest
            {
                Id = PackageId,
                Version = PackageVersion,
                Assembly = assemblyEntry,
                RegistrationType = "Axolotl2D.Generated.AxolotlGeneratedModuleRegistration",
                Entrypoint = string.IsNullOrWhiteSpace(Entrypoint) ? null : Entrypoint,
                SignerId = string.IsNullOrWhiteSpace(SigningKeyPath) ? null : SignerId,
                Dependencies = dependencies,
                Assets = assetMetadata
            };
            var contents = Assets.Select(item => new AxolotlPackageContent(item.GetMetadata("EntryName"),
                    item.GetMetadata("ContentType"), item.ItemSpec))
                .Append(new AxolotlPackageContent(assemblyEntry, AxolotlPackageFormat.AssemblyContentType, AssemblyPath))
                .Concat(ModuleAssemblies.Select(item => new AxolotlPackageContent("$module/" + Path.GetFileName(item.ItemSpec),
                    AxolotlPackageFormat.AssemblyContentType, item.ItemSpec)))
                .ToArray();
            using ECDsa? key = string.IsNullOrWhiteSpace(SigningKeyPath) ? null : ECDsa.Create();
            if (key is not null)
            {
                if (string.IsNullOrWhiteSpace(SignerId))
                    throw new InvalidOperationException("AxolotlSignerId is required when AxolotlSigningKey is set.");
                key.ImportFromPem(File.ReadAllText(SigningKeyPath!));
            }
            AxolotlPackageWriter.Write(OutputPath, manifest, contents, key);
            Log.LogMessage(MessageImportance.High, "Created Axolotl package {0}", OutputPath);
            return true;
        }
        catch (Exception exception)
        {
            Log.LogErrorFromException(exception, showStackTrace: true);
            return false;
        }
    }
}
